### ISSUE TITLE
"up" input not working

### ISSUE THREAD

**Issue by bkdfkup** [twocolors/node-red-contrib-apple-tv-x#1]
Hey there. Great node, simple to use, however i am having issues with the "up" command, and only that command. All other inputs work as expected. Have you experienced this behavior previously?

**Comment by twocolors** [comment]
thx, plz try version 0.3.2

**Comment by bkdfkup** [comment]
Perfect. Works like a charm! Thank you.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
