### ISSUE TITLE
launch_app not working in 0.5.1

### ISSUE THREAD

**Issue by langmeister** [twocolors/node-red-contrib-apple-tv-x#10]
Following the RFE to allow IPs/IDs to be manually specified #9 , the launch_app parameter no longer works (but same worked in 0.5.0):

when sending `msg.payload` set to `launch_app=com.netflix.Netflix`

**debug output**
Error: Command failed: atvremote --airplay-credentials abcdefghijklmnopqrstuvwxyz launch_app=com.netflix.Netflix
Scan Results
[...]

From the debug message, it would appear that the command isn't passing the actual device.

Sending a simple command, like "play" and "pause" continues to work fine.

**Node configs (to reproduce)**
Injection Node: 
`[{"id":"bd7c8d34.dc5d38","type":"inject","z":"c45155cd.0e34c8","name":"Launch Netflix","topic":"","payload":"launch_app=com.netflix.Netflix","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":550,"y":1040,"wires":[["caa4d47d.366338"]]}]`

ATV Out: 
`[{"id":"caa4d47d.366338","type":"atvx-out","z":"c45155cd.0e34c8","name":"","atvx":"e7158f3.0ee17f","skip_deprecated":false,"x":750,"y":1300,"wires":[]},{"id":"e7158f3.0ee17f","type":"atvx-config","z":"","name":"Big Screen (manual)","backend":"pyatv","companion":"684aea51228e5c7b68064b148e34471af6736937f831b6795c3751592cf048fe:add0564b0387070eb9796c559797ec5a82d5f0ed16d3914b971ae9ef61cf6fc9:32353041323034422d343136352d344233412d394430362d363042363345443943453430:64373132643230312d623063642d343363332d386334372d393163633465646335373162","debug":true}]`

ATV In:
`[{"id":"66b3dfa3.5298e","type":"atvx-in","z":"c45155cd.0e34c8","name":"New ATV","atvx":"e7158f3.0ee17f","x":190,"y":1300,"wires":[["caa4d47d.366338"]]},{"id":"e7158f3.0ee17f","type":"atvx-config","z":"","name":"Big Screen (manual)","backend":"pyatv","companion":"684aea51228e5c7b68064b148e34471af6736937f831b6795c3751592cf048fe:add0564b0387070eb9796c559797ec5a82d5f0ed16d3914b971ae9ef61cf6fc9:32353041323034422d343136352d344233412d394430362d363042363345443943453430:64373132643230312d623063642d343363332d386334372d393163633465646335373162","debug":true}]`

**Comment by twocolors** [comment]
try 0.5.2

**Comment by twocolors** [comment]
fix in 1.0.0
