### ISSUE TITLE
No matching distribution found for audio-metadata>=0.11.1

### ISSUE THREAD

**Issue by ektoekto** [twocolors/node-red-contrib-apple-tv-x#14]
![Näyttökuva 2022-04-04 145903](https://user-images.githubusercontent.com/102966018/161539172-e818ab1e-bc73-47dc-a27b-e1a036650def.png)

I'm trying to install this to my raspberry Pi and got next error.

**Comment by twocolors** [comment]
Hello, I don't have a solution. it is not clear to me why you have version 0.8.2 installed

now is https://github.com/postlund/pyatv/releases/tag/v0.10.0

try 

`sudo pip3 install -Iv pyatv==0.10.0` (https://stackoverflow.com/questions/5226311/installing-specific-package-version-with-pip)

**Comment by ektoekto** [comment]
So running that command reviled the underlying issue, i think. 
![Näyttökuva 2022-04-06 173640](https://user-images.githubusercontent.com/102966018/162000209-f7d13999-f8fc-43ed-8daf-fc25693c7fff.png)

For some reason, my Python is 3,5. 

![Näyttökuva 2022-04-06 173906](https://user-images.githubusercontent.com/102966018/162000577-cbce933e-e4ab-45b1-ba31-50677503ba6d.png)

I'll close the ticket for now and try to get that updated.
