### ISSUE TITLE
Node Red fails after installing node

### ISSUE THREAD

**Issue by icare88** [twocolors/node-red-contrib-apple-tv-x#2]
Hello! For information, here is the problem I have juste after installing the node. I had to run NodeRed in safe mode and uninstall it to recover normal operation. Thanks for your work.

Error: connect ECONNREFUSED 127.0.0.1:6668
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6668
}
7 May 13:35:19 - [red] Uncaught Exception:
7 May 13:35:19 - abort(Error: connect ECONNREFUSED 127.0.0.1:6668). Build with -s ASSERTIONS=1 for more info.
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=20s expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 7.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
7 May 13:35:42 - [info]
Welcome to Node-RED
===================
7 May 13:35:42 - [info] Node-RED version: v1.3.4
7 May 13:35:42 - [info] Node.js  version: v12.20.0
7 May 13:35:42 - [info] Linux 5.4.79-v7+ arm LE

**Comment by twocolors** [comment]
I know about this bug, the problem is busy tcp.
plz show all error logs, you copy not full logs 

+ and list install node

**Comment by icare88** [comment]
Thanks for your reply! Enclosed the full logs, and below the list of the nodes.

node-red-contrib-alexa-home-skill 
node-red-contrib-apple-tv-x 
node-red-contrib-fs 
node-red-contrib-homekit-bridged 
node-red-contrib-node-lifx 
node-red-contrib-play-audio 
node-red-contrib-tuya-smart-device 
node-red-contrib-virtual-smart-home 
node-red-contrib-zigbee 
node-red-contrib-zigbee2mqtt 
node-red-contrib-zigbee2mqtt-devices 
node-red-dashboard 
node-red-node-pi-gpio 
node-red-node-ping 
node-red-node-random 
node-red-node-rbe 
node-red-node-serialport 
node-red-node-smooth 
node-red-node-tail

[Log.txt](https://github.com/twocolors/node-red-contrib-apple-tv-x/files/6461440/Log.txt)

**Comment by twocolors** [comment]
try 0.3.3 and you add not full logs ):
