### ISSUE TITLE
Feature request: playing/idle/pause status

### ISSUE THREAD

**Issue by doomedsardines** [twocolors/node-red-contrib-apple-tv-x#3]
Great node! Thank you! Finally, something that works in Node Red and no need to use HomeAssistant to get ATV status.
However, I have a request, in HA ATV integration can distinguish between play, pause or idle. It would be great to have this here as well. Idle and playing is implemented already (with isPlaying being true or false), but paused is not.
And in my view it rather important since I e.g do not want to turn on the lights full for a short break but only if I stopped the movie, or when it's totally finished.

**Comment by twocolors** [comment]
for full support, you have to wait until the package is updated https://github.com/evandcoleman/node-appletv I will only implement a wrapper, you can read more about errors and features here https://github.com/lukasroegner/homebridge-apple-tv-remote/issues/46

but as soon as the opportunity arises or another solution I will definitely add

thanks for the idea and kind words

**Comment by doomedsardines** [comment]
@twocolors thanks for the explanation! Let's wait then.

**Comment by doomedsardines** [comment]
Issue closed, based on latest updates
