### ISSUE TITLE
Can the reboot command be added please?

### ISSUE THREAD

**Issue by houser42** [twocolors/node-red-contrib-apple-tv-x#4]
Can the reboot command that you can get by long-pressing menu and home on the apple remote be added?
Would be really useful! Many thanks!

**Comment by twocolors** [comment]
what is your apple tv version, this combination does not work for me (apple tv 4k)

**Comment by houser42** [comment]
Hello @twocolors 
I have an Apple TV 4K (A1842) and it works fine in node red for me.

**Comment by postlund** [comment]
I think that command only works with the physical remote control, I haven't managed to get it working with the one in iOS (or pyatv).
