### ISSUE TITLE
Appltv 4k not recognised in docker

### ISSUE THREAD

**Issue by Jai-Gogineni** [twocolors/node-red-contrib-apple-tv-x#7]
Hi,

I’m using node red official docker image. When I try to pair my Apple TV 4K I’m getting just an error “ No devices retrieved, check your Apple TVs connection settings”. ATV is Running.

I am using below command

`sudo docker run -it --net=host -v node_red_data:/data --name nodered5 nodered/node-red` still not able to recognise

**Comment by twocolors** [comment]
oh, this node not support tvOS 15 , more read https://github.com/lukasroegner/homebridge-apple-tv-remote/issues/114

**Comment by Jai-Gogineni** [comment]
Thank you !

**Comment by twocolors** [comment]
@Jai-Gogineni try new version and backend pyatv
