### ISSUE TITLE
Possible to manually add ATV ?

### ISSUE THREAD

**Issue by langmeister** [twocolors/node-red-contrib-apple-tv-x#9]
Due to networking issues, the pyatv scan isn't finding all my devices, but it can see them when specifying the IP address.

When creating a note in the atvs-config node panel, one is limited to what the scan turns up.  

I'd like a way to be able to manually specify an IP address.

**Comment by twocolors** [comment]
try 0.5.1

**Comment by langmeister** [comment]
That's awesome; it works a treat - ty!
